In [12]:
pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in c:\users\candi\appdata\roaming\python\python313\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\candi\appdata\roaming\python\python313\site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\candi\appdata\roaming\python\python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\candi\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\candi\appdata\roaming\python\python313\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\candi\appdata\roaming\python\python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [29]:
import pandas as pd

In [30]:
import os

print(os.getcwd())

C:\Users\candi\HowardPython

In [31]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'Costumer_Shopping_Behavior_Analysis.ipynb', 'customer_shopping_behavior_dataset.csv']

In [32]:
import pandas as pd
print(pd.__version__)

2.3.3

In [33]:
import pandas as pd

df = pd.read_csv("customer_shopping_behavior_dataset.csv")
df.head()

,Customer_ID,Age,Gender,City,Membership,Visit_Frequency,Preferred_Category,Average_Spend,Payment_Method,Online_Shopping,Discount_Used,Items_Purchased,Satisfaction_Rating
0,C001,24,Female,Manila,Gold,Weekly,Clothing,3200,Credit Card,Yes,Yes,5,5
1,C002,31,Male,Cebu,Silver,Monthly,Electronics,8500,GCash,Yes,No,2,4
2,C003,27,Female,Davao,Bronze,Weekly,Beauty,1800,Cash,No,Yes,4,4
3,C004,45,Male,Quezon City,Gold,Daily,Groceries,2400,Debit Card,No,No,12,5
4,C005,38,Female,Pasig,Silver,Monthly,Home,5200,Credit Card,Yes,Yes,3,5

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Customer_ID          30 non-null     object
 1   Age                  30 non-null     int64
 2   Gender               30 non-null     object
 3   City                 30 non-null     object
 4   Membership           25 non-null     object
 5   Visit_Frequency      30 non-null     object
 6   Preferred_Category   30 non-null     object
 7   Average_Spend        30 non-null     int64
 8   Payment_Method       30 non-null     object
 9   Online_Shopping      30 non-null     object
 10  Discount_Used        30 non-null     object
 11  Items_Purchased      30 non-null     int64
 12  Satisfaction_Rating  30 non-null     int64
dtypes: int64(4), object(9)
memory usage: 3.2+ KB

In [35]:
df.describe()

             Age  Average_Spend  Items_Purchased  Satisfaction_Rating
count  30.000000      30.000000        30.000000            30.000000
mean   33.100000    4566.666667         4.966667             4.533333
std     7.707363    3127.005104         3.872835             0.507416
min    21.000000    1200.000000         1.000000             4.000000
25%    27.000000    2325.000000         2.250000             4.000000
50%    32.500000    3400.000000         4.000000             5.000000
75%    38.750000    5975.000000         5.000000             5.000000
max    47.000000   12500.000000        15.000000             5.000000

In [36]:
df.describe(include='all')

,Customer_ID,Age,Gender,City,Membership,Visit_Frequency,Preferred_Category,Average_Spend,Payment_Method,Online_Shopping,Discount_Used,Items_Purchased,Satisfaction_Rating
count,30,30.000000,30,30,25,30,30,30.000000,30,30,30,30.000000,30.000000
unique,30,NaN,2,12,3,3,8,NaN,4,2,2,NaN,NaN
top,C001,NaN,Female,Manila,Gold,Weekly,Electronics,NaN,Credit Card,Yes,Yes,NaN,NaN
freq,1,NaN,15,3,10,14,5,NaN,9,21,18,NaN,NaN
mean,NaN,33.100000,NaN,NaN,NaN,NaN,NaN,4566.666667,NaN,NaN,NaN,4.966667,4.533333
std,NaN,7.707363,NaN,NaN,NaN,NaN,NaN,3127.005104,NaN,NaN,NaN,3.872835,0.507416
min,NaN,21.000000,NaN,NaN,NaN,NaN,NaN,1200.000000,NaN,NaN,NaN,1.000000,4.000000
25%,NaN,27.000000,NaN,NaN,NaN,NaN,NaN,2325.000000,NaN,NaN,NaN,2.250000,4.000000
50%,NaN,32.500000,NaN,NaN,NaN,NaN,NaN,3400.000000,NaN,NaN,NaN,4.000000,5.000000
75%,NaN,38.750000,NaN,NaN,NaN,NaN,NaN,5975.000000,NaN,NaN,NaN,5.000000,5.000000
max,NaN,47.000000,NaN,NaN,NaN,NaN,NaN,12500.000000,NaN,NaN,NaN,15.000000,5.000000

In [37]:
df.isnull().sum()

Customer_ID            0
Age                    0
Gender                 0
City                   0
Membership             5
Visit_Frequency        0
Preferred_Category     0
Average_Spend          0
Payment_Method         0
Online_Shopping        0
Discount_Used          0
Items_Purchased        0
Satisfaction_Rating    0
dtype: int64

In [ ]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))

In [38]:
df.isnull().sum()

Customer_ID            0
Age                    0
Gender                 0
City                   0
Membership             5
Visit_Frequency        0
Preferred_Category     0
Average_Spend          0
Payment_Method         0
Online_Shopping        0
Discount_Used          0
Items_Purchased        0
Satisfaction_Rating    0
dtype: int64

In [39]:
df.columns = df.columns.str.lower()
print(df.columns.tolist())

['customer_id', 'age', 'gender', 'city', 'membership', 'visit_frequency', 'preferred_category', 'average_spend', 'payment_method', 'online_shopping', 'discount_used', 'items_purchased', 'satisfaction_rating']

In [40]:
labels = ['Young Adult', 'Adult', 'Middle-age', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels = labels)

In [41]:
df[['age','age_group']].head(10)

   age    age_group
0   24  Young Adult
1   31        Adult
2   27  Young Adult
3   45       Senior
4   38   Middle-age
5   29        Adult
6   22  Young Adult
7   34   Middle-age
8   41       Senior
9   26  Young Adult

In [44]:
frequency_mapping = {
    'Daily': 1,
    'Weekly': 7,
    'Monthly': 30
}

df['purchase_frequency_days'] = df['visit_frequency'].map(frequency_mapping)

In [45]:
df[['visit_frequency', 'purchase_frequency_days']].head(10)

  visit_frequency  purchase_frequency_days
0          Weekly                        7
1         Monthly                       30
2          Weekly                        7
3           Daily                        1
4         Monthly                       30
5          Weekly                        7
6         Monthly                       30
7          Weekly                        7
8         Monthly                       30
9          Weekly                        7

In [46]:
df[['online_shopping','discount_used']].head(10)

  online_shopping discount_used
0             Yes           Yes
1             Yes            No
2              No           Yes
3              No            No
4             Yes           Yes
5             Yes            No
6             Yes           Yes
7             Yes            No
8              No           Yes
9             Yes           Yes

In [57]:
(df['online_shopping'] == df['discount_used']).all()

np.False_

In [58]:
pip install psycopg2-binary sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\candi\appdata\roaming\python\python313\site-packages (2.9.12)
Requirement already satisfied: sqlalchemy in c:\programdata\anaconda3\lib\site-packages (2.0.43)
Requirement already satisfied: greenlet>=1 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (3.2.4)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\programdata\anaconda3\lib\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

In [64]:
from sqlalchemy import create_engine

username = "postgres"
password = "Howard0190"
host = "localhost"
port = "5432"
database = "costumer_behavior"  # check spelling

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")

table_name = "costumer"  # check spelling
df.to_sql(table_name, engine, if_exists="replace", index=False)

print(f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'costumer' in database 'costumer_behavior'.